# Generated by Django 5.0.7 on 2024-07-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover', models.ImageField(default='', upload_to='covers')),
                ('type', models.CharField(choices=[('EPIC', 'Epic Fantasy'), ('SCIFI', 'Sci Fi')], default='EPIC', max_length=5)),
                ('bookContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasybooksapp.book')),
            ],
        ),
    ]
