# Generated by Django 5.0.7 on 2024-07-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybooksapp', '0004_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userBookmarks',
        ),
    ]
