# Generated by Django 5.0.7 on 2024-08-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybooksapp', '0007_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='user_name',
        ),
    ]
