# Generated by Django 5.0.7 on 2024-08-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybooksapp', '0010_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
    ]
