# Generated by Django 5.0.7 on 2024-08-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybooksapp', '0013_alter_customuser_userreads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
    ]
