# Generated by Django 5.0.7 on 2024-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybooksapp', '0016_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='userId',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
