# Generated by Django 5.0.7 on 2024-08-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybooksapp', '0017_bookmark_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='book',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='page',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='userId',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
