# Generated by Django 5.0.7 on 2024-08-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybooksapp', '0018_alter_bookmark_book_alter_bookmark_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='book',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='page',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='userId',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
